# Aprendendo OpenCV

## Leitura de imagem

anotações do processo de aprendizado de uso da biblioteca OpenCV em Python a partir das notas do site [LearnOpenCV](https://learnopencv.com/getting-started-with-opencv/)

O método `cv2.imread` lê uma imagem em qualquer formato de imagem e retorna como um array de matrizes, cada matriz possui um valor de cor *BGR* (Blue - Green - Red). Ele pode receber como segundo argumento uma flag que diz como a imagem deve ser representada:

* cv2.IMREAD_UNCHANGED / -1 = ...
* cv2.IMREAD_GRAYSCALE / 0 = lê a imagem em escala de cinza
* cv2.IMREAD_COLOR / 1 = lê a imagem como está

O método `cv2.imshow` pega o array e exibe a imagem

Os métodos `cv2.waitKey()` e `cv2.destroyAllWindows()` são utilizados para parar a exibição da imagem, ao apertart qualquer tecla (0)

In [1]:
import cv2

img = cv2.imread('./test.jpg')
img_grayscale = cv2.imread('./test.jpg', cv2.IMREAD_GRAYSCALE)
img_unchanged = cv2.imread('./test.jpg', cv2.IMREAD_UNCHANGED)

cv2.imshow('imagem', img)
cv2.imshow('imagem grayscale', img_grayscale)
cv2.imshow('imagem nao alterada', img_unchanged)

print(img)

cv2.waitKey(0)
cv2.destroyAllWindows()


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/mateusglg/.local/lib/python3.10/site-packages/cv2/qt/plugins"


[[[ 67 142 228]
  [ 67 142 228]
  [ 68 143 229]
  ...
  [ 46 108 179]
  [ 46 108 179]
  [ 46 108 179]]

 [[ 68 143 229]
  [ 68 143 229]
  [ 69 144 230]
  ...
  [ 46 108 179]
  [ 46 108 179]
  [ 46 108 179]]

 [[ 69 145 228]
  [ 70 146 229]
  [ 70 146 229]
  ...
  [ 46 108 179]
  [ 46 108 179]
  [ 46 108 179]]

 ...

 [[ 81 144 224]
  [ 81 144 224]
  [ 80 143 223]
  ...
  [ 18  62 125]
  [ 18  62 125]
  [ 18  62 125]]

 [[ 84 147 227]
  [ 81 144 224]
  [ 78 141 221]
  ...
  [ 18  62 125]
  [ 18  62 125]
  [ 18  62 125]]

 [[ 84 147 227]
  [ 81 144 224]
  [ 78 141 221]
  ...
  [ 18  62 125]
  [ 18  62 125]
  [ 18  62 125]]]


## Redimensionamento de imagens

A propriedade `img.shape` returna uma tripla que possui os valores de largura, altura e canais.

Para mudar o tamanho da imagem, é utilizado o método `cv2.resize`, que recebe a imagem, a tupla de tamanho e uma flag de interpolação


In [2]:
import cv2
import numpy as np

image = cv2.imread('test2.jpg')

h,w,c = image.shape
print("Original heigth and width: ", h, "x", w)



Original heigth and width:  353 x 1024


In [3]:
down_width = 300
down_height = 200
down_points = (down_width, down_height)
resized_down = cv2.resize(image, down_points, interpolation=cv2.INTER_LINEAR)

In [4]:
up_width = 600
up_height = 400
up_points = (up_width, up_height)

resized_up = cv2.resize(image, up_points, interpolation = cv2.INTER_LINEAR)

In [5]:
cv2.imshow('Resized Down by defining height and width', resized_down)
cv2.waitKey()
cv2.imshow('Resized Up image by defining height and width', resized_up)
cv2.waitKey()
cv2.destroyAllWindows()

Também é possível redimensionar utilizando um fator de escalamento

In [6]:
# Scaling Up the image 1.2 times by specifying both scaling factors
scale_up_x = 1.2
scale_up_y = 1.2
# Scaling Down the image 0.6 times specifying a single scale factor.
scale_down = 0.6
 
scaled_f_down = cv2.resize(image, None, fx= scale_down, fy= scale_down, interpolation= cv2.INTER_LINEAR)
scaled_f_up = cv2.resize(image, None, fx= scale_up_x, fy= scale_up_y, interpolation= cv2.INTER_LINEAR)

In [7]:
cv2.imshow('Resized Down by defining scaling factor', scaled_f_down)
cv2.waitKey()
cv2.imshow('Resized Up image by defining scaling factor', scaled_f_up)
cv2.waitKey()

cv2.destroyAllWindows()

### Métodos de interpolação

Os métodos de **Interpolação** disponíveis no OpenCV são:

* INTER_AREA = usa a relação de pixels da área para reamostragem. É útil para reduzir o tamanho de uma imagem.
* INTER_CUBIC = usa a interpolação bicúbica para redimencionar a imagem. Esse método age nos pixels em uma vizinhança 4x4. Com isso, ele tira média dos pesos dos 16 pixels para criar um novo pixel interpolado
* INTER_LINEAR = Funciona como o CUBIC, mas usa vizinhanças menores de 2x2.
* INTER_NEAREST = usa o conceito de vizinhos próximos para a interpolação.

In [8]:
res_inter_nearest = cv2.resize(image, None, fx= scale_down, fy= scale_down, interpolation= cv2.INTER_NEAREST)
res_inter_linear = cv2.resize(image, None, fx= scale_down, fy= scale_down, interpolation= cv2.INTER_LINEAR)
res_inter_area = cv2.resize(image, None, fx= scale_down, fy= scale_down, interpolation= cv2.INTER_AREA)

In [9]:
# Concatenate images in horizontal axis for comparison
vertical= np.concatenate((res_inter_nearest, res_inter_linear, res_inter_area), axis = 0)
# Display the image Press any key to continue
cv2.imshow('Inter Nearest :: Inter Linear :: Inter Area', vertical)

cv2.waitKey()

cv2.destroyAllWindows()

## Cropping / recorte de imagem



Para recortar uma imagem, é só utilizar as características de matriz dela e utilizar os slices de python

In [10]:
import cv2
import numpy as np
 
img = cv2.imread('test.jpg')
cv2.imshow("original", img)

cv2.waitKey(0)
 
# Cropping an image
cropped_image = img[80:280, 150:330]
 
# Display cropped image
cv2.imshow("cropped", cropped_image)
 
# Save the cropped image
cv2.imwrite("Cropped Image.jpg", cropped_image)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

(682, 1024, 3)


É possível utilizar a função de recorte para recortar a imagem em pequenas subunidades

In [12]:
img = cv2.imread("test.jpg")
image_copy = img.copy() 
imgheight = img.shape[0]
imgwidth = img.shape[1]

In [13]:
M = 76
N = 104
x1 = 0
y1 = 0
 
for y in range(0, imgheight, M):
    for x in range(0, imgwidth, N):
        if (imgheight - y) < M or (imgwidth - x) < N:
            break
             
        y1 = y + M
        x1 = x + N
 
        # check whether the patch width or height exceeds the image width or height
        if x1 >= imgwidth and y1 >= imgheight:
            x1 = imgwidth - 1
            y1 = imgheight - 1
            #Crop into patches of size MxN
            tiles = image_copy[y:y+M, x:x+N]
            #Save each patch into file directory
            cv2.imwrite('saved_patches/'+'tile'+str(x)+'_'+str(y)+'.jpg', tiles)
            cv2.rectangle(img, (x, y), (x1, y1), (0, 255, 0), 1)
        elif y1 >= imgheight: # when patch height exceeds the image height
            y1 = imgheight - 1
            #Crop into patches of size MxN
            tiles = image_copy[y:y+M, x:x+N]
            #Save each patch into file directory
            cv2.imwrite('saved_patches/'+'tile'+str(x)+'_'+str(y)+'.jpg', tiles)
            cv2.rectangle(img, (x, y), (x1, y1), (0, 255, 0), 1)
        elif x1 >= imgwidth: # when patch width exceeds the image width
            x1 = imgwidth - 1
            #Crop into patches of size MxN
            tiles = image_copy[y:y+M, x:x+N]
            #Save each patch into file directory
            cv2.imwrite('saved_patches/'+'tile'+str(x)+'_'+str(y)+'.jpg', tiles)
            cv2.rectangle(img, (x, y), (x1, y1), (0, 255, 0), 1)
        else:
            #Crop into patches of size MxN
            tiles = image_copy[y:y+M, x:x+N]
            #Save each patch into file directory
            cv2.imwrite('saved_patches/'+'tile'+str(x)+'_'+str(y)+'.jpg', tiles)
            cv2.rectangle(img, (x, y), (x1, y1), (0, 255, 0), 1)

In [14]:
cv2.imshow("Patched Image",img)
cv2.imwrite("patched.jpg",img)
  
cv2.waitKey()
cv2.destroyAllWindows()

## Rotação de imagens


In [2]:
image = cv2.imread('./test.jpg')

height, width = image.shape[:2]

center = (width/2, height/2)

rotate_matrix = cv2.getRotationMatrix2D(center=center, angle=45, scale=1)

print(rotate_matrix)

rotated_image = cv2.warpAffine(src=image, M=rotate_matrix, dsize=(width, height))

cv2.imshow('Original image', image)
cv2.imshow('Rotated image', rotated_image)

cv2.waitKey(0)

cv2.imwrite('rotate_image.jpg', rotated_image)

[[  0.70710678   0.70710678 -91.16208435]
 [ -0.70710678   0.70710678 461.91525958]]


True

: 

## Espaços de cor

O espaço de cor RGB possui as seguintes propriedades:
* É um espaço de cor aditivo onde cores são obtidas com a combinação linear de valores de Vermelho, Azul e Verde
* Os três canais são correlacionados pela quantidade de luz na superfície



In [ ]:
cubos = cv2.imread('two-cubes.png')